name: Run Java tests on push to master

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: mvn test

      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: test-results

      - name: Show test results
        run: cat test-results/TEST-*